# Generated by Django 3.1.4 on 2020-12-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20201213_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='latitud',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='longitud',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
