# Generated by Django 3.1.4 on 2020-12-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20201213_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='geoestado',
        ),
        migrations.AddField(
            model_name='usuario',
            name='estadogeo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
