# Generated by Django 3.1.4 on 2020-12-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20201213_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estadogeo',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
